name: Deploy to GKE (Dev Branch)

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: mqed-ai-research-tool-466620
  GKE_CLUSTER: mqed-ai-research-tool-dev
  GKE_ZONE_OR_REGION: us-central1-a
  IMAGE_NAME: mqed-research-tool
  IMAGE_TAG: ${{ github.sha }}
  DEPLOYMENT_NAME: mqed-research-tool-dev
  ARTIFACT_REPOSITORY: mqed-ai-artifact-repository-docker
  CONTAINER_PORT: 8000
  SERVICE_PORT: 80

jobs:
  build_and_deploy:
    name: Build, Push, and Deploy to Development
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_DEV_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate Docker to Google Container Registry (GCR)
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to GCR
        run: docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE_OR_REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run (Dev)
        run: |
          gcloud run deploy ${{ env.DEPLOYMENT_NAME }} \
            --image=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=${{ env.CONTAINER_PORT }}

      - name: Get Cloud Run URL
        id: get-url
        run: |
          echo "url=$(gcloud run services describe ${{ env.DEPLOYMENT_NAME }} --platform=managed --region=us-central1 --format='value(status.url)')" >> $GITHUB_OUTPUT

      - name: Output service URL
        run: |
          echo "Cloud Run service URL: ${{ steps.get-url.outputs.url }}"
