name: Deploy to GKE (Main Branch)

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mqed-ai-research-tool
  GKE_CLUSTER: mqed-ai-research-tool-prod
  GKE_ZONE_OR_REGION: us-central1
  IMAGE_NAME: mqed-research-tool
  IMAGE_TAG: ${{ github.sha }}
  DEPLOYMENT_NAME: mqed-research-tool-prod
  CONTAINER_PORT: 8000
  SERVICE_PORT: 80

jobs:
  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-prod-app.com
    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_PROD_SA_KEY }}

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          region: ${{ env.GKE_ZONE_OR_REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Production GKE
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.IMAGE_NAME }}=gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --record